name: todo_app
description: A new Flutter project.

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.2.8
  path_provider: ^2.0.12
  awesome_notifications: ^0.8.2
  intl: ^0.18.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter:
  # Define assets here
  assets:
    - assets/icon/appicon.png
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"      # Configures Android app icons
  ios: true                     # Configures iOS app icons
  image_path: "assets/icon/appicon.png"  # Path to the app icon
